config/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

SLUG_REGEX = r'[-a-zA-Z0-9_]+'

urlpatterns = patterns('',
    url(r'^$', 'shops.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<slug>%s)/$' % SLUG_REGEX, 'shops.views.detail', name='shop'),

)

shops/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Shop(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    slug = models.SlugField(unique=True)
    address = models.CharField(max_length=255)
    website = models.URLField(blank=True)
    phone = models.CharField(max_length=255)
    #image = models.ImageField(max_length=255, upload_to="shops", blank=True)
    image = models.URLField(blank=True)
    timetable = models.CharField(max_length=400)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=255, blank=True)
    categories = models.CharField(max_length=255)
    lat = models.FloatField(null=True)
    lng = models.FloatField(null=True)
   
    class Meta:
        ordering = ('name',)

    def get_absolute_url(self):
        return reverse('shop',args=(self.slug,))

    def __str__(self):
        return self.name

shops/views.py
from django.views.generic import ListView, DetailView
from .models import Shop

class Home(ListView):
    model = Shop
    template_name = "home.html"

home = Home.as_view()

class Detail(DetailView):
    model = Shop
    template_name = "shops/detail.html"

detail = Detail.as_view()

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{% block title %}Commercesdepont.fr{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
{% block css %}
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
{% endblock %}
</head>
<body>
<div class="container">
    <div class="header">
        <ul class="nav nav-pills pull-right">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="#">Evenements</a></li>
            <li><a href="#">Rejoindre</a></li>
            <li><a href="#">Se connecter</a></li>
        </ul>
        <h3 class="text-muted">Commercesdepont.fr</h3>
    </div>
</div>
{% block content %}
{% endblock %}

{% block js %}
<script src="{% static "js/jquery.js" %}"></script>
{#<script src="{% static "js/bootstrap.js" %}"></script>#}
{% endblock %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="homepage row-fluid text-center">
        <div class="search-form text-center">
            <input type="text" id="search" class="form-control" placeholder="Que recherchez vous ?"/>
        </div>
        {% for shop in shop_list %}
        <a href="{% url 'shop' shop.slug %}">
            <div class="shop shop-homepage" 
                data-filtering="{{ shop.name }}
                {{ shop.categories }}
                {{ shop.description }}
                {{ shop.website }}">
                 <img src="http://commercesdepont.fr/wp-content/uploads/{{ shop.image }}" />
                 <h4>{{ shop.name }}</h4>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block js %}
{{ block.super }}
<script>
function refresh(){
    var filter = $('#search').get(0).value;
    $('.shop').each(function(i,shop){   
        if(filter != "" && $(shop).attr("data-filtering").toLowerCase().indexOf(filter.toLowerCase()) == -1){
            $(shop).hide()
        }else{
            $(shop).show()
        }
    })
}
$('#search').keyup(refresh);
</script>
{% endblock %}

templates/nope.html
{% extends "base.html" %}

{% block content %}
<h1>Nope, this page isn't made yet.</h1>
<h3>Advice: It's not a bug, it a feature</h3>
<div class="text-center"><img style="max-width:50%" src="http://i.imgur.com/VoFZVo3.jpg" alt="sad cat" /></div>
{% endblock %}

templates/shops/detail.html
{% extends "base.html" %}

{% block title %}{{ shop.name }} - {{ block.super }} {% endblock %}

{% block content %}
{% include "shops/shop.html" %}
{% endblock %}

templates/shops/shop.html
<div class="container">
<div class="shop" >
    <img class="thumbnail" src="http://commercesdepont.fr/wp-content/uploads/{{ shop.image }}" />
    <h4 class="name">
        <a href="{% url 'shop' shop.slug %}">{{ shop.name }}</a>
    </h4>
    <div class="website">
        <label>Site web:</label> <a href="{{ shop.website }}">{{ shop.website }}</a>
    </div>
    <div class="phone">
        <label>Tel.:</label> {{ shop.phone}}
    </div>
    <div class="timetable">
        <label>Horaires:</label> {{ shop.timetable}}
    </div>
    <div class="address">
        <label>Adresse:</label> {{ shop.address }}, 60700 Pont-Sainte-Maxence
    </div>
    <p class="description">
        {{ shop.description|striptags }}
    </p>
</div>
</div>